# Generated by Django 3.1 on 2020-08-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ashokley',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Open', models.FloatField()),
                ('High', models.FloatField()),
                ('Low', models.FloatField()),
                ('Close', models.FloatField()),
                ('Adj_close', models.FloatField()),
                ('Volume', models.FloatField()),
                ('Date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Cipla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Open', models.FloatField()),
                ('High', models.FloatField()),
                ('Low', models.FloatField()),
                ('Close', models.FloatField()),
                ('Adj_close', models.FloatField()),
                ('Volume', models.FloatField()),
                ('Date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Eichermotors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Open', models.FloatField()),
                ('High', models.FloatField()),
                ('Low', models.FloatField()),
                ('Close', models.FloatField()),
                ('Adj_close', models.FloatField()),
                ('Volume', models.FloatField()),
                ('Date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Nifty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Open', models.FloatField()),
                ('High', models.FloatField()),
                ('Low', models.FloatField()),
                ('Close', models.FloatField()),
                ('Adj_close', models.FloatField()),
                ('Volume', models.FloatField()),
                ('Date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Open', models.FloatField()),
                ('High', models.FloatField()),
                ('Low', models.FloatField()),
                ('Close', models.FloatField()),
                ('Adj_close', models.FloatField()),
                ('Volume', models.FloatField()),
                ('Date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Open', models.FloatField()),
                ('High', models.FloatField()),
                ('Low', models.FloatField()),
                ('Close', models.FloatField()),
                ('Adj_close', models.FloatField()),
                ('Volume', models.FloatField()),
                ('Date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tatasteel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Open', models.FloatField()),
                ('High', models.FloatField()),
                ('Low', models.FloatField()),
                ('Close', models.FloatField()),
                ('Adj_close', models.FloatField()),
                ('Volume', models.FloatField()),
                ('Date', models.DateTimeField()),
            ],
        ),
    ]
