# Generated by Django 3.1 on 2020-08-15 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_integer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Integer',
        ),
    ]
